spring:
  redis:
    host: 172.30.255.171
    port: 6379
    database: 2 # Redis数据库选择默认为0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数(-1表示没有限制)
        max-wait: -1 # 连接池最大阻塞等待时间
        max-idle: 8 # 连接池最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接
