spring:
  security:
    user:
      name: root
      password: root

  freemarker:
    template-loader-path: classpath:/templates
    # 关闭缓存 上线修改为true
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
