server:
  port: 8081

spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3306/database?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    alibaba:
      seata:
        tx-service-group: order

seata:
  service:
    vgroup-mapping:
      order: default
    grouplist:
      default: 172.30.255.171:8091
